- hosts: linux
  become: true
  gather_facts: false
  collections:
    - ansible.builtin
  tasks: 
  - name: copy default html file to web servers
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  - name: Restart web services
    service:
      name: apache2
      state: restarted 



